server:
  port: 8080

spring:
  application:
    name: multiplication
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
  datasource:
    url: jdbc:postgresql://postgres/postgres
    username: postgres
    password: demo
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  rabbitmq:
    host: rabbit-mq

amqp:
  multiplication:
    exchange:
      name: multiplication-exchange
    attempt-done-event:
      routing-key: multiplication.attempt.done
service:
  random:
    up: 100
keycloak:
  realm: ms-book-realm
  auth-server-url: http://localhost:8180/auth
  public-client: true
  resource: ms-book-backend
  bearer-only: true
  cors: true
debug: true








