server:
  port: 8080
spring:
  application:
    name: multiplication
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL:postgres-social-multiplication-service}/postgres
    username: ${POSTGRES_USERNAME:postgres}
    password: ${POSTGRES_PASSWORD:demo}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  rabbitmq:
    host: ${RABBIT_HOST:rabbit-mq-service}
    port: ${RABBIT_PORT:5672}
amqp:
  multiplication:
    exchange:
      name: multiplication-exchange
    attempt-done-event:
      routing-key: multiplication.attempt.done
service:
  random:
    up: 100
keycloak:
  realm: ms-book-realm
  auth-server-url: http://${KEYCLOAK_URL:keycloak-common-service}/auth
  resource: ms-book-backend
  bearer-only: true
  cors: true
  credentials:
    secret: 10de2b6a-aa4c-4a05-84ea-e29de645fc93
  ssl-required: none
debug: true