apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbit-mq
  labels:
    app: rabbit-mq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbit-mq
  template:
    metadata:
      labels:
        app: rabbit-mq
    spec:
      containers:
        - name: rabbit-mq
          image: rabbitmq:3.8.3-management
          ports:
            - name: broker
              containerPort: 5672
            - name: management
              containerPort: 15672
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-social-multiplication
  labels:
    app: postgres-social-multiplication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-social-multiplication
  template:
    metadata:
      labels:
        app: postgres-social-multiplication
    spec:
      containers:
        - name: postgres
          image: postgres:12.2
          ports:
           - containerPort: 5432
          env:
          - name: POSTGRES_PASSWORD
            value: demo
---
apiVersion: v1
kind: Service
metadata:
  name: rabbit-mq-service
  labels:
    svc: rabbit-mq-service
spec:
  ports:
    - name: mq
      port: 5672
      protocol: TCP
    - name: management
      port: 15672
      protocol: TCP
  selector:
    app: rabbit-mq
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-social-multiplication-service
  labels:
    svc: postgres-social-multiplication-service
spec:
  ports:
    - port: 5432
      protocol: TCP
  selector:
    app: postgres-social-multiplication