apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    app: kafka-service
spec:
  ports:
    - port: 9092
      name: server
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
spec:
  serviceName: kafka-service
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  podManagementPolicy: Parallel
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          env:
            - name: "INDEX_FROM_HOSTNAME"
              value: "true"
            - name: "KAFKA_ZOOKEEPER_CONNECT"
              value: "zk-cs:2181"
            - name: "ADVERTISED_LISTENERS_FROM_HOSTNAME"
              value: "true"
            - name: "KUBERNETES_POD"
              value: "kafka"
            - name: "KUBERNETES_SERVICE"
              value: "kafka-service"
          imagePullPolicy: Always
          image: "sergeykulagin/kafka:latest"
          ports:
            - containerPort: 9092
              name: server
#          volumeMounts:
#            - name: data-zookeeper
#              mountPath: /var/lib/zookeeper
#              readOnly: false
#  volumeClaimTemplates:
#    - metadata:
#        name: data-zookeeper
#        annotations:
#          volume.beta.kubernetes.io/storage-class: "nfs"
#      spec:
#        accessModes: [ "ReadWriteMany" ]
#        resources:
#          requests:
#            storage: 1Gi