apiVersion: v1
kind: Service
metadata:
  name: zk-service
  labels:
    app: zk-service
spec:
  ports:
    - port: 2181
      name: client
    - port: 2888
      name: server
    - port: 3888
      name: leader-election
    - port: 8080
      name: admin
  clusterIP: None
  selector:
    app: zk
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-external-service-0
spec:
  type: NodePort
  selector:
    "statefulset.kubernetes.io/pod-name": zk-0
  ports:
    - port: 8080
      nodePort: 30035
      name: admin
    - port: 2181
      nodePort: 30030
      name: client
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-external-service-1
spec:
  type: NodePort
  selector:
    "statefulset.kubernetes.io/pod-name": zk-1
  ports:
    - port: 8080
      nodePort: 30036
      name: admin
    - port: 2181
      nodePort: 30031
      name: client
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-external-service-2
spec:
  type: NodePort
  selector:
    "statefulset.kubernetes.io/pod-name": zk-2
  ports:
    - port: 8080
      nodePort: 30037
      name: admin
    - port: 2181
      nodePort: 30032
      name: client
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zk
spec:
  serviceName: zk-service
  replicas: 3
  selector:
    matchLabels:
      app: zk
  podManagementPolicy: Parallel
  template:
    metadata:
      labels:
        app: zk
    spec:
      containers:
        - name: zookeeper
          env:
            - name: "ZOO_SERVERS"
              value: "server.1=zk-0.zk-service:2888:3888;2181 server.2=zk-1.zk-service:2888:3888;2181 server.3=zk-2.zk-service:2888:3888;2181"
          imagePullPolicy: Always
          image: "sergeykulagin/zookeeper:3.5.7"
          ports:
            - containerPort: 2181
              name: client
            - containerPort: 2888
              name: server
            - containerPort: 3888
              name: leader-election
            - containerPort: 8080
              name: admin
          volumeMounts:
            - name: data-zookeeper
              mountPath: /data
              readOnly: false
  volumeClaimTemplates:
    - metadata:
        name: data-zookeeper
        annotations:
          volume.beta.kubernetes.io/storage-class: "nfs"
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 1Gi