server:
  port: 8080
spring:
  application:
    name: multiplication
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
  datasource:
    url: jdbc:postgresql://${POSTGRES_URL:localhost:5432}/multiplication
    username: ${POSTGRES_USERNAME:multiplication}
    password: ${POSTGRES_PASSWORD:multiplication}
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
amqp:
  multiplication:
    exchange:
      name: multiplication-exchange
    attempt-done-event:
      routing-key: multiplication.attempt.done
service:
  random:
    up: 100