apiVersion: apps/v1
kind: Deployment
metadata:
  name: nfs-client-provisioner
  labels:
    app: nfs-client-provisioner
  namespace: default
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: nfs-client-provisioner
  template:
    metadata:
      labels:
        app: nfs-client-provisioner
    spec:
      serviceAccountName: nfs-client-provisioner
      nodeSelector:
        "kubernetes.io/hostname": node-1
      containers:
        - name: nfs-client-provisioner
          image: quay.io/external_storage/nfs-client-provisioner-arm:latest
          volumeMounts:
            - name: nfs-client-root
              mountPath: /persistentvolumes
          env:
            - name: PROVISIONER_NAME
              value: external-storage/nfs-client
            - name: NFS_SERVER
              value: 10.0.0.40
            - name: NFS_PATH
              value: "/export/nsf-0"
      volumes:
        - name: nfs-client-root
          nfs:
            server: 10.0.0.40
            path: /export/nsf-0
